### PR TITLE
Added PSR6 storage

### PR DESCRIPTION
**Pull request by Nyholm**
The PSR6 for cache implementation was release a couple of weeks ago. This PR adds a storage for a PSR6 implementation.

### CODE REVIEW

**Comment by frankdejonge** [comment]
@Nyholm 👍 Merged! I'm in Singapore now, will tag when I'm back in Amsterdam (with a working laptop)

**Comment by Nyholm** [comment]
Awesome. Thank you!

**Comment by eXtreme** [comment]
@frankdejonge any chance of tagging?

**Comment by frankdejonge** [comment]
@Nyholm @eXtreme tagged 1.0.3 :+1:

**Comment by eXtreme** [comment]
@frankdejonge :clap:

**Pull request merged**
